### ISSUE TITLE
`detail_train`関数のLoRAマージ処理で`lbws`パラメータ欠落によるエラー修正

### ISSUE THREAD

**Issue by zomian87x** [tori29umai0123/CoppyLora_webUI#3]
## 問題の概要
Google Colabを使って、`CopyLora_WebUI_colab.py`を実行する際、`detail_train`関数内（638行目付近）のLoRAマージ処理において、`args_dict`に`lbws`パラメータが設定されていないため、`sdxl_merge_lora.py`の`merge`関数実行時に`AttributeError`が発生します。

## エラー内容
AttributeError: 'Namespace' object has no attribute 'lbws'

## エラーの発生箇所
`/content/drive/MyDrive/CoppyLora_webUI/sd-scripts/networks/sdxl_merge_lora.py`の377行目：
if args.lbws:

## 修正内容
CopyLora_WebUI_colab.py にCopyLora_WebUI.py と同じになるよう、以下のように 、`args_dict`に`"lbws": []`を追加：

args_dict = {
   "save_precision": "bf16",
   "precision": "float",
   # ... 他のパラメータ ...
   "shuffle": True,
   "lbws": []  # 追加
}

## 修正後の動作
- エラーが解消され、LoRAのマージ処理が正常に完了

## 関連ファイル
- `CopyLora_WebUI_colab.py`
- `sd-scripts/networks/sdxl_merge_lora.py`

**Comment by tori29umai0123** [comment]
修正しました。ご指摘ありがとうございます！
